### ISSUE TITLE
能否提供chm/pdf版本的文件

### ISSUE THREAD

**Issue by wklken** [sixu05202004/pythontutorial#1]
感觉是目前网上能找到最好的中文文档了，尝试自己编译没成功，囧，能否提供下pdf或者chm版本供下载？   wklken@yeah.net

**Comment by zepinglee** [comment]
#10 解决了这个问题

**Comment by sixu05202004** [comment]
请使用 https://pypi.python.org/pypi/rst2pdf 自己尝试生成PDF，可以参看 http://www.hankcs.com/program/python/the-use-of-rst2pdf-to-expand-sphinx-to-generate-pdf.html

**Comment by v1-hermit** [comment]
编epub吧，pdf错误太多了

**Comment by v1-hermit** [comment]
`processing Pythontutorial.tex... Importing extension module 'vectorpdf'
index appetite interpreter introduction controlflow datastructures modules inputoutput errors classes stdlib stdlib2 whatnow interactive floatingpoint appendix WARNING: too many values to unpack
Traceback (most recent call last):
  File "d:\python27\lib\site-packages\rst2pdf-0.93.dev_r0-py2.7.egg\rst2pdf\pdfbuilder.py", line 122, in write
    appendices=opts.get('pdf_appendices', self.config.pdf_appendices) or [])
  File "d:\python27\lib\site-packages\rst2pdf-0.93.dev_r0-py2.7.egg\rst2pdf\pdfbuilder.py", line 209, in assemble_doctree
    index_nodes=genindex_nodes(genindex)
  File "d:\python27\lib\site-packages\rst2pdf-0.93.dev_r0-py2.7.egg\rst2pdf\pdfbuilder.py", line 385, in genindex_nodes
    for entryname, (links, subitems) in entries:
ValueError: too many values to unpack
**FAILED**`
